[package]
name = "sms"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
tempfile = "3.20.0"
tokio = { version = "1.46.1", features = ["full"] }
